name: 'develop'
on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*
jobs:
  src:
      strategy:
        fail-fast: false
        matrix:
          os-image:
            - ubuntu-22.04
            - macos-12
          version:
            - opencv: 3.4.19
            - opencv: 4.7.0
          exclude:
            - os-image: macos-12
              version:
                opencv: 3.4.19
          include:
            - os-image: ubuntu-22.04
              version:
                opencv: 4.7.0-static
      runs-on: ${{ matrix.os-image }}
      env:
        Atlas_ROOT_DIR: /usr/include/ # for cmake to find lapacke.h
        OPENCV_VERSION: ${{ matrix.version.opencv }}
      steps:
        - uses: actions/checkout@v3

        - name: Cache dependencies
          uses: actions/cache@v3
          with:
            path: ~/build
            key: src-${{ matrix.version.opencv }}-${{ matrix.os-image }}

        - name: Install dependencies
          env:
            OS_FAMILY: ${{ runner.os }}
          run: ci/install.sh
          shell: bash

        - uses: dtolnay/rust-toolchain@stable

        - name: Test project
          env:
            OS_FAMILY: ${{ runner.os }}
          run: ci/script.sh
          shell: bash
